In [43]:
import torch
from transformers import AutoTokenizer, AutoModel
from pathlib import Path
from einops import rearrange, repeat
import os
import numpy as np

In [44]:
# Load pre-trained model and tokenizer
model_name = "huggyllama/llama-13b"
# model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# Tokenize input sequence
input_sequence = "This film is terrible, best to pass."
input_tokens = tokenizer.tokenize(input_sequence)
print(input_tokens)
input_tokens.insert(0, "<bos>") # beginning of sentence
print(input_tokens)

# Encode input sequence
input_ids = tokenizer.encode(input_sequence, return_tensors="pt")
print(input_ids)

decoded = tokenizer.convert_ids_to_tokens(input_ids[0])
print(decoded)

# Generate hidden states
outputs = model(input_ids, output_hidden_states=True)

Loading checkpoint shards: 100%|██████████| 3/3 [00:18<00:00,  6.07s/it]
Some weights of the model checkpoint at huggyllama/llama-13b were not used when initializing LlamaModel: ['lm_head.weight']
- This IS expected if you are initializing LlamaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


['▁This', '▁film', '▁is', '▁terrible', ',', '▁best', '▁to', '▁pass', '.']
['<bos>', '▁This', '▁film', '▁is', '▁terrible', ',', '▁best', '▁to', '▁pass', '.']
tensor([[    1,   910,  2706,   338, 16403, 29892,  1900,   304,  1209, 29889]])
['<s>', '▁This', '▁film', '▁is', '▁terrible', ',', '▁best', '▁to', '▁pass', '.']


In [45]:
hidden_states = outputs.hidden_states
print(hidden_states[0].shape)
print(len(hidden_states))
cat_hidden_states = torch.cat(hidden_states[:-1], dim=0)
print(cat_hidden_states.shape)

torch.Size([1, 10, 5120])
41
torch.Size([40, 10, 5120])


In [46]:
def load_all_reporters(num_layers: int, prefix_path: str) -> torch.Tensor:
    reporters_weights = []
    for i in range(num_layers):
        reporter_path = f"{prefix_path}/layer_{i}.pt"
        reporter = torch.load(reporter_path)
        reporters_weights.append(reporter['weight'].cpu())
    stacked = torch.cat(reporters_weights, dim=0)
    return stacked

# path = '/home/waree/elk-reporters/huggyllama/llama-13b/sethapun/imdb_misspelled_0/llama13b-imdb0/reporters'
path = '/mnt/ssd-1/spar/jon/elk-reporters/gpt2/imdb/agitated-driscoll/reporters'
reporter_paths = [
    '/home/jon/elk-reporters/huggyllama/llama-13b/azhx/counterfact-easy/stoic-jang/reporters',
]
# reporter_weights = load_all_reporters(model.config.num_hidden_layers, path)
# print(reporter_weights.shape)
for path in reporter_paths:
    reporter_weights = load_all_reporters(model.config.num_hidden_layers, path)
    print(reporter_weights.shape)

torch.Size([40, 5120])


In [47]:
# Use einsum to do multiplication 
result = torch.einsum('bse,be->bs', cat_hidden_states, reporter_weights)
print(result[0])
print(result.shape)

sigmoid_result = torch.sigmoid(result)
softmax_result = torch.softmax(result, dim = -1)
torch.set_printoptions(precision=1)

tensor([-0.0,  0.0,  0.0,  0.0,  0.0, -0.0, -0.0, -0.0,  0.0, -0.0],
       grad_fn=<SelectBackward0>)
torch.Size([40, 10])


In [48]:
print(result.shape)

torch.Size([40, 10])


In [49]:
print(sigmoid_result.shape)

torch.Size([40, 10])


In [50]:
print(softmax_result.shape)

torch.Size([40, 10])


In [51]:
import plotly.graph_objs as go
import plotly.io as pio
import torch
from IPython.display import HTML
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

# Create color scale for heatmap
color_scale = [[0, '#FFFFFF'], [1, '#FF0000']] # white to red

# Convert tensor to numpy array and detach gradients
credences = result.detach().numpy()

padded_text = np.array([[" " * 2 + "{:.2f}".format(value) + " " * 2 for value in row] for row in credences])

# Create plotly heatmap
heatmap = go.Heatmap(
    z=credences, 
    colorscale=color_scale,
    text=padded_text,  # Set the text to be equal to z
    texttemplate="%{text}", 
    textfont=dict(color='black', size=12),  # Set the text color and size
)

# Create plot layout
layout = go.Layout(title='Credences for Input Tokens',
                width=800,  # Set the width of the plot
                height=800,  # Set the height of the plot
                   xaxis=dict(tickvals=list(range(len(input_tokens))),
                              ticktext=input_tokens,
                              tickangle=45))

# Create plotly figure
fig = go.Figure(data=[heatmap], layout=layout)
# fig = fig.update_traces(text=input_tokens, texttemplate="%{text}", hovertemplate=None)

# Display plotly figure
# iplot(fig)

# print(padded_text)
input_tokens

['<bos>',
 '▁This',
 '▁film',
 '▁is',
 '▁terrible',
 ',',
 '▁best',
 '▁to',
 '▁pass',
 '.']

In [52]:
words_corresponding_to_credences = np.array([[" " * 2 + word + " " * 2 for word in input_tokens] for layer_num in range(len(credences))])

heatmap = go.Heatmap(
    z=credences,
    colorscale=color_scale,
    text=words_corresponding_to_credences,  # Set the text to be equal to z
    texttemplate="%{text}",
    textfont=dict(color='black', size=12),  # Set the text color and size
)

# Create plot layout
layout = go.Layout(title='Credences for Input Tokens',
                width=800,  # Set the width of the plot
                height=800,  # Set the height of the plot

                     xaxis=dict(tickvals=list(range(len(input_tokens))),
                                ticktext=input_tokens,
                                tickangle=45))

# Create plotly figure
fig = go.Figure(data=[heatmap], layout=layout)

# Display plotly figure
print(credences[-1].shape)
iplot(fig)


(10,)


In [65]:
import matplotlib.pyplot as plt

def colorize(words, credences):
    
    max_color = float(max(credences))
    min_color = float(min(credences))
    normalized_credences = (credences - min_color) / (max_color - min_color)
    
    cmap = plt.get_cmap('Blues')
    
    template = '<span class="barcode"; style="color: black; background-color: {}" title="{}">{}</span>'
    colored_string = ''
    
    for word, credence, norm_credence in zip(words, credences, normalized_credences):
        word = word.replace('▁', ' ')
        color = cmap(norm_credence)[:3]
        color = 'rgb(' + str(int(color[0]*255)) + ',' + str(int(color[1]*255)) + ',' + str(int(color[2]*255)) + ')'
        print(word, credence, norm_credence)
        colored_string += template.format(color, str(credence), word)
    
    return colored_string

# example usage:
words = input_tokens
colors = credences[-1] # associated values

# Colorizing the text
print(words, colors)
colored_string = colorize(words, colors)

# To display the colored string in Jupyter Notebook
display(HTML(colored_string))

['<bos>', '▁This', '▁film', '▁is', '▁terrible', ',', '▁best', '▁to', '▁pass', '.'] [14.801093 21.4402   25.842049 25.527487  6.562271 45.627815 26.71216
 35.150642 -9.107204 41.0222  ]
<bos> 14.801093 0.43680078
 This 21.4402 0.5580962
 film 25.842049 0.6385172
 is 25.527487 0.6327702
 terrible 6.562271 0.28627878
, 45.627815 1.0
 best 26.71216 0.65441406
 to 35.150642 0.80858374
 pass -9.107204 0.0
. 41.0222 0.9158562


In [67]:
# make it into a function of type signature reporter, sentences -> visualization

def load_all_reporters(num_layers: int, prefix_path: str) -> torch.Tensor:
    reporters_weights = []
    for i in range(num_layers):
        reporter_path = f"{prefix_path}/layer_{i}.pt"
        reporter = torch.load(reporter_path)
        reporters_weights.append(reporter['weight'].cpu())
    stacked = torch.cat(reporters_weights, dim=0)
    return stacked

# path = '/home/waree/elk-reporters/huggyllama/llama-13b/sethapun/imdb_misspelled_0/llama13b-imdb0/reporters'
path = '/mnt/ssd-1/spar/jon/elk-reporters/gpt2/imdb/agitated-driscoll/reporters'
reporter_paths = [
    '/home/jon/elk-reporters/huggyllama/llama-13b/azhx/counterfact-easy/stoic-jang/reporters',
]
# reporter_weights = load_all_reporters(model.config.num_hidden_layers, path)
# print(reporter_weights.shape)
# for path in reporter_paths:
#     reporter_weights = 

reporter_weights = load_all_reporters(model.config.num_hidden_layers, reporter_paths[0])

def viz(reporter_weights, sentence):
    input_ids = tokenizer.encode(sentence, return_tensors="pt")
    words = tokenizer.convert_ids_to_tokens(input_ids[0])
    outputs = model(input_ids, output_hidden_states=True)
    hidden_states = outputs.hidden_states
    # print(hidden_states[0].shape)
    # print(len(hidden_states))
    cat_hidden_states = torch.cat(hidden_states[:-1], dim=0)
    # Use einsum to do multiplication 
    result = torch.einsum('bse,be->bs', cat_hidden_states, reporter_weights)
    # print(result[0])
    # print(result.shape)

    # sigmoid_result = torch.sigmoid(result)
    # softmax_result = torch.softmax(result, dim = -1)
    torch.set_printoptions(precision=1)
    credences = result.detach().numpy()
    print(words, credences[-1])
    colored_string = colorize(words, credences[-1])
    display(HTML(colored_string))

viz(reporter_weights, "I love this movie so much")
viz(reporter_weights, "Wow this movie is terrible")



['<s>', '▁I', '▁love', '▁this', '▁movie', '▁so', '▁much'] [ 14.801093  36.474953  13.489883  12.165128  16.554022  15.309718
 -13.057999]
<s> 14.801093 0.56243557
 I 36.474953 1.0
 love 13.489883 0.5359641
 this 12.165128 0.5092191
 movie 16.554022 0.5978247
 so 15.309718 0.57270396
 much -13.057999 0.0


['<s>', '▁W', 'ow', '▁this', '▁movie', '▁is', '▁terrible'] [14.801093  32.42535   33.502026  22.945139  38.00926   21.254108
 11.0020275]
<s> 14.801093 0.14066847
 W 32.42535 0.79324394
ow 33.502026 0.83311015
 this 22.945139 0.44221902
 movie 38.00926 1.0
 is 21.254108 0.37960505
 terrible 11.0020275 0.0


# Sanity Checks

In [55]:
# # Use einsum to do multiplication 

# reporter_weights_repeat = repeat(reporter_weights, 'b e -> b c e', c=len(input_tokens) + 1)
# result = torch.einsum('bse,bse->bs', cat_hidden_states, reporter_weights_repeat)
# print(result.shape)

# sigmoid_result = torch.sigmoid(result)
# softmax_result = torch.softmax(result, dim = -1)
# torch.set_printoptions(precision=1)

In [56]:
print(result)

tensor([[-5.1e-03,  1.5e-02,  1.8e-02,  1.3e-02,  4.8e-03, -6.8e-03, -1.9e-03,
         -2.7e-02,  2.2e-02, -2.7e-02],
        [-6.5e-01,  7.4e-02, -1.0e-01, -1.2e-01,  2.0e-01, -7.1e-02, -3.7e-02,
         -3.2e-02,  6.1e-02, -8.2e-02],
        [-2.3e+00, -1.1e+00, -2.6e-01, -1.1e+00, -5.4e-01, -1.6e+00, -4.8e-01,
         -5.9e-01, -8.8e-01, -1.6e+00],
        [-5.6e+01,  9.4e-01,  1.0e+00,  8.2e-01,  9.9e-01,  8.0e-01,  4.3e-01,
          3.7e-01,  6.7e-01,  6.2e-01],
        [-1.4e+01,  2.3e+00,  2.3e+00,  1.6e+00,  1.4e+00,  8.3e-01,  1.1e+00,
          2.5e-01,  4.8e-01,  5.1e-01],
        [-3.8e+01,  2.8e+00,  2.6e+00,  1.3e+00,  1.4e+00,  9.1e-01,  6.2e-01,
          2.1e-01,  1.2e-01,  4.3e-01],
        [ 4.5e+01, -2.6e+00, -3.2e+00, -1.5e+00, -1.9e+00, -1.1e+00, -4.0e-01,
         -4.9e-01, -1.7e-01, -4.8e-01],
        [ 3.3e+01, -2.7e+00, -3.8e+00, -1.4e+00, -1.9e+00, -1.3e+00, -9.0e-01,
         -8.8e-01, -3.5e-01, -4.4e-01],
        [ 1.7e+00,  3.7e+00,  5.2e+00,  2.7e+00,